export const banks: string[] = [
    "Amex Bank of Canada",
    "Bank of America (Canada Branch)",
    "Bank of Canada",
    "Bank of Montreal (BMO)",
    "Bank of Nova Scotia",
    "Bank West",
    "B2B Bank",
    "Bridgewater Bank",
    "Business Development Bank of Canada (BDC)",
    "Canadian Imperial Bank of Commerce (CIBC)",
    "Canadian Tire Bank (CTB)",
    "Canadian Western Bank",
    "Capital One",
    "Citi Canada",
    "CFF Bank",
    "Churchill International Property Corp",
    "CS Alterna Bank",
    "Credit Suisse Securities (Canada), Inc",
    "Desjardins Group",
    "Deutsche Bank Securities Ltd",
    "DirectCash Bank (DC Bank)",
    "Dundee Corporation",
    "Exchange Bank of Canada (EBC)",
    "First Nations Bank of Canada",
    "General Bank of Canada",
    "HomEquity Bank",
    "HSBC Bank Canada",
    "ING Direct Canada (Tangerine)",
    "Jameson Bank",
    "Laurentian Bank of Canada",
    "Manulife Bank of Canada",
    "MBNA Canada",
    "MonCana Bank of Canada",
    "National Bank of Canada",
    "Power Corporation of Canada (POW)",
    "President's Choice Financial",
    "Royal Bank of Canada (RBC)",
    "Street Capital Bank of Canada",
    "Tangerine Bank",
    "TD Canada Trust",
    "Toronto-Dominion Bank (TD)",
    "Vancity",
    "Vancity Community Investment Bank",
    "VersaBank",
    "Wealth One Bank of Canada (WOBC)",
    "Zag Bank"
  ];
  